services:
    wordpress:
        image: wordpress:6.5.0-php8.3-fpm-alpine
        restart: unless-stopped
        volumes:
            - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./config/wordpress/wp-config.php:/var/www/html/wp-config.php
            - wordpress:/var/www/html
            - ./wp-content:/var/www/html/wp-content
        env_file:
            - .env
        environment:
            WORDPRESS_CONFIG_EXTRA: |
                define('CORE_UPGRADE_SKIP_NEW_BUNDLED' , true);
                define('WP_DEFAULT_THEME', 'blank-canvas-3');
    app:
        image: node:22.0.0-alpine
        user: node
        depends_on:
            - wordpress
        restart: unless-stopped
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app/
        environment:
            NODE_ENV: production
        env_file:
            - .env
        init: true
        command: |
            sh -c "
                if [ ! -d node_modules ]; then
                    npm install
                fi
                if [ ! -f dist/server.js ]; then
                    npm run build
                fi
                node dist/server.js
            "
    webserver:
        image: nginx:1.25.4-alpine
        depends_on:
            - wordpress
            - app
        restart: unless-stopped
        volumes:
            - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./config/nginx/snippets:/etc/nginx/snippets
            - wordpress:/var/www/html/!/wordpress
            - ./wp-content:/var/www/html/!/wordpress/wp-content
            - phpmyadmin:/var/www/html/!/phpmyadmin
        env_file:
            - .env
        environment:
            ERROR_LOG: stdout
            ACCESS_LOG: stderr
    ssl:
        image: steveltn/https-portal:1.23.1
        depends_on:
            - webserver
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - ./.ssl:/var/lib/https-portal
        env_file:
            - .env
        environment:
            # DOMAINS: 'example.com -> http://webserver:80 #production'
            # DOMAINS: 'staging.example.com -> http://webserver:80 #staging'
            DOMAINS: 'localhost -> http://webserver:80 #local'
            # allow larger file uploads
            CLIENT_MAX_BODY_SIZE: 64M

volumes:
    phpmyadmin:
    wordpress:
